import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.vision': 'Vision & Mission',
    'nav.services': 'Services',
    'nav.free-addons': 'Free Add-ons',
    'nav.additional': 'Additional Services',
    'nav.schedule': 'Work Schedule',
    'nav.why': 'Why Choose Us',
    'nav.contact': 'Contact',
    'nav.whatsapp': 'WhatsApp',
    'nav.language': 'العربية',
    
    // Hero
    'hero.title': 'Elevate Your Property',
    'hero.subtitle': 'Integrated Solutions for Cleaning & Facility Management',
    'hero.description': 'Get a tailored service plan and a transparent quote. Contact us directly for a fast response.',
    'hero.cta': 'Request Assessment on WhatsApp',
    
    // About
    'about.title': 'About Us',
    'about.description': 'Aman Al Khair is a Saudi startup specializing in cleaning, maintenance, and facility management for residential and commercial complexes. Our mission is to improve quality of life through innovative solutions and professional execution.',
    'about.quality': '100% Commitment to Quality',
    'about.team': '✓ Dedicated Team',
    'about.cr': 'CR: 7041589726',
    
    // Vision & Mission
    'vision.title': 'Vision & Mission',
    'vision.vision-title': 'Vision',
    'vision.vision-text': 'To be the leading choice in Saudi Arabia by excelling in quality, reliability, and attention to the smallest details.',
    'vision.mission-title': 'Mission',
    'vision.mission-text': 'To enhance our clients\' quality of life by delivering integrated, innovative solutions in facility management and cleaning, adhering to the highest standards.',
    
    // Services
    'services.title': 'Our Services',
    'services.subtitle': 'What We Offer',
    'services.description': 'Comprehensive cleaning, maintenance, and facility management solutions tailored to your needs',
    'services.cleaning': 'Cleaning',
    'services.maintenance': 'Maintenance',
    'services.facility': 'Facility Management',
    'services.waste': 'Daily Waste Removal',
    'services.deep': 'Deep Cleaning (Lobbies & Corridors)',
    'services.glass': 'Glass & Window Polishing',
    'services.roof': 'Roof & Tank Cleaning',
    'services.pest': 'Pest-Control Spraying',
    'services.categories.core': 'Core Services',
    'services.categories.maintenance': 'Maintenance',
    'services.categories.management': 'Management',
    'services.categories.waste': 'Waste Management',
    'services.categories.specialized': 'Specialized Cleaning',
    'services.categories.glass': 'Glass Care',
    'services.categories.exterior': 'Exterior Services',
    'services.categories.pest': 'Pest Control',
    'services.descriptions.cleaning': 'Professional cleaning solutions for all environments',
    'services.descriptions.maintenance': 'Comprehensive maintenance and repair services',
    'services.descriptions.facility': 'Complete facility management solutions',
    'services.descriptions.waste': 'Efficient daily waste removal and disposal',
    'services.descriptions.deep': 'Deep cleaning for lobbies and corridors',
    'services.descriptions.glass': 'Professional glass and window polishing',
    'services.descriptions.roof': 'Roof and tank cleaning services',
    'services.descriptions.pest': 'Effective pest control and prevention',
    'services.features.eco': 'Eco-friendly products',
    'services.features.staff': 'Trained staff',
    'services.features.quality': 'Quality guarantee',
    'services.features.preventive': 'Preventive maintenance',
    'services.features.support': '24/7 support',
    'services.features.technicians': 'Expert technicians',
    'services.features.planning': 'Strategic planning',
    'services.features.optimization': 'Cost optimization',
    'services.features.monitoring': 'Performance monitoring',
    'services.features.recycling': 'Recycling programs',
    'services.features.hygienic': 'Hygienic disposal',
    'services.features.schedules': 'Regular schedules',
    'services.features.equipment': 'Advanced equipment',
    'services.features.thorough': 'Thorough cleaning',
    'services.features.odor': 'Odor elimination',
    'services.features.streak': 'Streak-free finish',
    'services.features.safety': 'Safety protocols',
    'services.features.results': 'Long-lasting results',
    'services.features.safety-equipment': 'Safety equipment',
    'services.features.inspection': 'Thorough inspection',
    'services.features.care': 'Preventive care',
    'services.features.chemicals': 'Safe chemicals',
    'services.features.monitoring-pest': 'Regular monitoring',
    'services.features.prevention': 'Prevention plans',
    'services.learn-more': 'Learn More',
    'services.cta.title': 'Ready to Get Started?',
    'services.cta.description': 'Contact us today to discuss your cleaning and maintenance needs. We\'ll provide you with a customized solution that fits your requirements and budget.',
    'services.cta.button': 'Get Free Quote',
    
    // Free Add-ons
    'addons.title': 'Free Add-ons',
    'addons.subtitle': 'Bonus Services Included',
    'addons.description': 'These valuable services are included at no extra cost with your main service package',
    'addons.parking': 'Parking Re-Marking & Numbering',
    'addons.spraying': 'Bi-Annual Insect Spraying',
    'addons.bins': 'Supply of Waste Bins',
    'addons.parking.description': 'Professional parking space re-marking and clear numbering for better organization',
    'addons.spraying.description': 'Comprehensive insect control treatment twice a year to keep your property pest-free',
    'addons.bins.description': 'High-quality waste bins supplied and maintained as part of your service',
    'addons.parking.features.1': 'Professional marking',
    'addons.parking.features.2': 'Clear numbering',
    'addons.parking.features.3': 'Better organization',
    'addons.parking.features.4': 'No extra cost',
    'addons.spraying.features.1': 'Bi-annual treatment',
    'addons.spraying.features.2': 'Pest prevention',
    'addons.spraying.features.3': 'Safe chemicals',
    'addons.spraying.features.4': 'Expert application',
    'addons.bins.features.1': 'Quality bins',
    'addons.bins.features.2': 'Regular maintenance',
    'addons.bins.features.3': 'Hygienic design',
    'addons.bins.features.4': 'Included service',
    'addons.cta.title': 'All Included in Your Package',
    'addons.cta.description': 'These premium add-ons come standard with our service packages - no hidden fees, no surprises',
    'addons.cta.button': 'View Full Package',
    'addons.included-no-cost': 'Included at No Extra Cost',
    'addons.package-part': 'Part of your service package',
    'addons.premium-value': 'Premium Value',
    'addons.no-hidden-fees': 'No Hidden Fees',
    'addons.premium-quality': 'Premium Quality',
    'addons.free-charge': 'Free of Charge',
    'addons.no-additional-costs': 'No additional costs',
    'addons.premium-addons': 'Premium Add-ons',
    'addons.included-automatically': 'Included automatically',
    'addons.support-available': 'Support Available',
    'addons.always-here-help': 'Always here to help',
    
    // Additional Services
    'additional.title': 'Additional Services',
    'additional.playground': 'Outdoor Children\'s Play Equipment Installation',
    'additional.security': 'Security Systems for Shared Entrances',
    'additional.canopies': 'Parking Canopies (Supply & Install)',
    'additional.landscape': 'Custom Landscape & Garden Design',
    'additional.elevator': 'Elevator Maintenance & Safety Assurance',
    
    // Work Schedule
    'schedule.title': 'Work Schedule',
    'schedule.subtitle': 'When We Work For You',
    'schedule.description': 'Flexible scheduling that adapts to your needs and ensures maximum convenience',
    'schedule.morning': 'Morning 07:00–11:00',
    'schedule.evening': 'Evening 16:00–20:00',
    'schedule.flexible': 'Flexible timing per client agreement',
    'schedule.vat': 'All prices include VAT',
    'schedule.morning.description': 'Early morning cleaning and maintenance services',
    'schedule.evening.description': 'Afternoon and evening service delivery',
    'schedule.flexible.description': 'Custom scheduling based on your requirements',
    'schedule.vat.description': 'Transparent pricing with no hidden costs',
    'schedule.morning.features.1': 'Early start',
    'schedule.morning.features.2': 'Fresh beginning',
    'schedule.morning.features.3': 'Minimal disruption',
    'schedule.evening.features.1': 'Convenient timing',
    'schedule.evening.features.2': 'After hours',
    'schedule.evening.features.3': 'Professional service',
    'schedule.flexible.features.1': 'Custom timing',
    'schedule.flexible.features.2': 'Client priority',
    'schedule.flexible.features.3': 'Adaptive scheduling',
    'schedule.vat.features.1': 'No hidden fees',
    'schedule.vat.features.2': 'Transparent pricing',
    'schedule.vat.features.3': 'Full compliance',
    'schedule.cta.title': 'Need Custom Timing?',
    'schedule.cta.description': 'We understand every property has unique scheduling needs. Contact us to arrange a personalized work schedule.',
    'schedule.cta.button': 'Request Custom Schedule',
    'schedule.daily-workflow': 'Daily Work Flow',
    'schedule.daily-workflow.description': 'See how our schedule adapts to your needs',
    'schedule.flexible-scheduling': 'Flexible Scheduling',
    'schedule.availability': 'Availability',
    'schedule.availability.description': 'Always ready to serve',
    'schedule.client-satisfaction': 'Client Satisfaction',
    'schedule.client-satisfaction.description': 'Your time, our priority',
    'schedule.scheduling': 'Scheduling',
    'schedule.scheduling.description': 'Adapts to your needs',
    'schedule.time.custom': 'Custom',
    'schedule.time.included': 'Included',
    'schedule.time.morning': '07:00 - 11:00',
    'schedule.time.evening': '16:00 - 20:00',
    
    // Why Choose Us
    'why.title': 'Why Choose Us',
    'why.quality-title': 'Unmatched Quality',
    'why.quality-text': 'Best materials and equipment for results beyond expectations.',
    'why.response-title': 'Quick Response',
    'why.response-text': 'Fast action, efficient emergency handling.',
    'why.team-title': 'Integrated Team',
    'why.team-text': 'Skilled technicians, professional service.',
    'why.sustainability-title': 'Sustainability & Reliability',
    'why.sustainability-text': 'Environmentally friendly, dependable.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.cta': 'Ready to elevate your property? Contact us today on WhatsApp for a free facility assessment.',
    'contact.email': 'Email',
    'contact.whatsapp-label': 'WhatsApp',
    'contact.address': 'Address',
    'contact.cr-label': 'CR',
    'contact.button': 'Talk to Us on WhatsApp',
    'contact.address-text': 'Riyadh – Ishbiliyah District',
    
    // Footer
    'footer.description': 'Professional cleaning and facility management solutions',
    'footer.links': 'Quick Links',
    'footer.contact-info': 'Contact Info',
    'footer.copyright': '© 2024 Aman Al Khair. All rights reserved.',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.vision': 'الرؤية والرسالة',
    'nav.services': 'الخدمات',
    'nav.free-addons': 'الإضافات المجانية',
    'nav.additional': 'خدمات إضافية',
    'nav.schedule': 'أوقات العمل',
    'nav.why': 'لماذا نحن',
    'nav.contact': 'تواصل معنا',
    'nav.whatsapp': 'واتساب',
    'nav.language': 'English',
    
    // Hero
    'hero.title': 'ارتقِ بمستوى ممتلكاتك',
    'hero.subtitle': 'حلول متكاملة للنظافة وإدارة المرافق',
    'hero.description': 'احصل على خطة خدمة مخصصة وعرض سعر شفاف. تواصل معنا مباشرةً للحصول على استجابة سريعة.',
    'hero.cta': 'اطلب تقييمك عبر واتساب',
    
    // About
    'about.title': 'من نحن',
    'about.description': 'أمان الخير شركة سعودية ناشئة متخصصة في خدمات النظافة والصيانة وإدارة المرافق للمجمعات السكنية والتجارية. نهدف لإحداث فرق في جودة الحياة عبر حلول مبتكرة وتنفيذ احترافي.',
    'about.quality': '%100 التزام بالجودة',
    'about.team': '✓ فريق متخصص',
    'about.cr': 'سجل تجاري: 7041589726',
    
    // Vision & Mission
    'vision.title': 'الرؤية والرسالة',
    'vision.vision-title': 'رؤيتنا',
    'vision.vision-text': 'أن نكون الخيار الأول في المملكة العربية السعودية من خلال التفوق في الجودة والموثوقية والاهتمام بأدق التفاصيل.',
    'vision.mission-title': 'رسالتنا',
    'vision.mission-text': 'تحسين جودة الحياة لعملائنا بتقديم حلول متكاملة ومبتكرة في إدارة المرافق والنظافة، مع الالتزام بأعلى معايير الاحترافية.',
    
    // Services
    'services.title': 'خدماتنا',
    'services.subtitle': 'ما نقدمه',
    'services.description': 'حلول شاملة للنظافة والصيانة وإدارة المرافق مصممة خصيصاً لاحتياجاتك',
    'services.cleaning': 'النظافة',
    'services.maintenance': 'الصيانة',
    'services.facility': 'إدارة المرافق',
    'services.waste': 'إزالة النفايات اليومية',
    'services.deep': 'تنظيف عميق للردهات والممرات',
    'services.glass': 'تلميع الواجهات الزجاجية',
    'services.roof': 'تنظيف الأسطح والخزانات',
    'services.pest': 'رش المبيدات الحشرية',
    'services.categories.core': 'الخدمات الأساسية',
    'services.categories.maintenance': 'الصيانة',
    'services.categories.management': 'الإدارة',
    'services.categories.waste': 'إدارة النفايات',
    'services.categories.specialized': 'التنظيف المتخصص',
    'services.categories.glass': 'العناية بالزجاج',
    'services.categories.exterior': 'الخدمات الخارجية',
    'services.categories.pest': 'مكافحة الآفات',
    'services.descriptions.cleaning': 'حلول تنظيف احترافية لجميع البيئات',
    'services.descriptions.maintenance': 'خدمات صيانة وإصلاح شاملة',
    'services.descriptions.facility': 'حلول إدارة مرافق متكاملة',
    'services.descriptions.waste': 'إزالة وتخلص فعالة من النفايات اليومية',
    'services.descriptions.deep': 'تنظيف عميق للردهات والممرات',
    'services.descriptions.glass': 'تلميع احترافي للزجاج والنوافذ',
    'services.descriptions.roof': 'خدمات تنظيف الأسطح والخزانات',
    'services.descriptions.pest': 'مكافحة آفات فعالة والوقاية منها',
    'services.features.eco': 'منتجات صديقة للبيئة',
    'services.features.staff': 'موظفون مدربون',
    'services.features.quality': 'ضمان الجودة',
    'services.features.preventive': 'صيانة وقائية',
    'services.features.support': 'دعم على مدار الساعة',
    'services.features.technicians': 'فنيون خبراء',
    'services.features.planning': 'تخطيط استراتيجي',
    'services.features.optimization': 'تحسين التكاليف',
    'services.features.monitoring': 'مراقبة الأداء',
    'services.features.recycling': 'برامج إعادة التدوير',
    'services.features.hygienic': 'تخلص صحي',
    'services.features.schedules': 'جداول منتظمة',
    'services.features.equipment': 'معدات متقدمة',
    'services.features.thorough': 'تنظيف شامل',
    'services.features.odor': 'القضاء على الروائح',
    'services.features.streak': 'نتيجة خالية من الخطوط',
    'services.features.safety': 'بروتوكولات السلامة',
    'services.features.results': 'نتائج طويلة الأمد',
    'services.features.safety-equipment': 'معدات السلامة',
    'services.features.inspection': 'فحص شامل',
    'services.features.care': 'رعاية وقائية',
    'services.features.chemicals': 'مواد كيميائية آمنة',
    'services.features.monitoring-pest': 'مراقبة منتظمة',
    'services.features.prevention': 'خطط الوقاية',
    'services.learn-more': 'اعرف المزيد',
    'services.cta.title': 'هل أنت مستعد للبدء؟',
    'services.cta.description': 'تواصل معنا اليوم لمناقشة احتياجاتك من النظافة والصيانة. سنقدم لك حلاً مخصصاً يناسب متطلباتك وميزانيتك.',
    'services.cta.button': 'احصل على عرض سعر مجاني',
    
    // Free Add-ons
    'addons.title': 'الإضافات المجانية',
    'addons.subtitle': 'خدمات إضافية مشمولة',
    'addons.description': 'هذه الخدمات القيمة مشمولة بدون أي تكلفة إضافية مع حزمة الخدمة الرئيسية',
    'addons.parking': 'إعادة تخطيط وترقيم المواقف',
    'addons.spraying': 'رش المبيدات الحشرية كل 6 أشهر',
    'addons.bins': 'توفير حاويات النفايات',
    'addons.parking.description': 'إعادة تخطيط احترافية لمواقف السيارات وترقيم واضح لتنظيم أفضل',
    'addons.spraying.description': 'معالجة شاملة لمكافحة الحشرات مرتين سنوياً لإبقاء ممتلكاتك خالية من الآفات',
    'addons.bins.description': 'صناديق نفايات عالية الجودة يتم توفيرها وصيانتها كجزء من خدمتك',
    'addons.parking.features.1': 'تخطيط احترافي',
    'addons.parking.features.2': 'ترقيم واضح',
    'addons.parking.features.3': 'تنظيم أفضل',
    'addons.parking.features.4': 'بدون تكلفة إضافية',
    'addons.spraying.features.1': 'معالجة نصف سنوية',
    'addons.spraying.features.2': 'منع الآفات',
    'addons.spraying.features.3': 'مواد كيميائية آمنة',
    'addons.spraying.features.4': 'تطبيق خبير',
    'addons.bins.features.1': 'صناديق عالية الجودة',
    'addons.bins.features.2': 'صيانة منتظمة',
    'addons.bins.features.3': 'تصميم صحي',
    'addons.bins.features.4': 'خدمة مشمولة',
    'addons.cta.title': 'كلها مشمولة في حزمتك',
    'addons.cta.description': 'هذه الإضافات المميزة تأتي قياسية مع حزم الخدمة لدينا - بدون رسوم خفية، بدون مفاجآت',
    'addons.cta.button': 'عرض الحزمة الكاملة',
    'addons.included-no-cost': 'مشمول بدون تكلفة إضافية',
    'addons.package-part': 'جزء من حزمة الخدمة',
    'addons.premium-value': 'قيمة مميزة',
    'addons.no-hidden-fees': 'بدون رسوم خفية',
    'addons.premium-quality': 'جودة مميزة',
    'addons.free-charge': 'مجاناً',
    'addons.no-additional-costs': 'بدون تكاليف إضافية',
    'addons.premium-addons': 'إضافات مميزة',
    'addons.included-automatically': 'مشمولة تلقائياً',
    'addons.support-available': 'الدعم متاح',
    'addons.always-here-help': 'دائماً هنا للمساعدة',
    
    // Additional Services
    'additional.title': 'خدمات إضافية',
    'additional.playground': 'تركيب ألعاب أطفال خارجية',
    'additional.security': 'أنظمة أمنية لأبواب المناطق المشتركة',
    'additional.canopies': 'مظلات مواقف (توريد وتركيب)',
    'additional.landscape': 'تصميم وتنسيق الحدائق',
    'additional.elevator': 'صيانة المصاعد وضمان سلامتها',
    
    // Work Schedule
    'schedule.title': 'أوقات العمل',
    'schedule.subtitle': 'متى نعمل من أجلك',
    'schedule.description': 'جدولة مرنة تتكيف مع احتياجاتك وتضمن أقصى راحة',
    'schedule.morning': 'صباحي 07:00–11:00',
    'schedule.evening': 'مسائي 16:00–20:00',
    'schedule.flexible': 'مواعيد مرنة حسب اتفاق العميل',
    'schedule.vat': 'جميع الأسعار شاملة ضريبة القيمة المضافة',
    'schedule.morning.description': 'خدمات تنظيف وصيانة في الصباح الباكر',
    'schedule.evening.description': 'تقديم الخدمات في فترة ما بعد الظهر والمساء',
    'schedule.flexible.description': 'جدولة مخصصة بناءً على متطلباتك',
    'schedule.vat.description': 'تسعير شفاف بدون تكاليف خفية',
    'schedule.morning.features.1': 'بداية مبكرة',
    'schedule.morning.features.2': 'بداية جديدة',
    'schedule.morning.features.3': 'حد أدنى من الاضطراب',
    'schedule.evening.features.1': 'توقيت مناسب',
    'schedule.evening.features.2': 'بعد ساعات العمل',
    'schedule.evening.features.3': 'خدمة احترافية',
    'schedule.flexible.features.1': 'توقيت مخصص',
    'schedule.flexible.features.2': 'أولوية العميل',
    'schedule.flexible.features.3': 'جدولة تكيفية',
    'schedule.vat.features.1': 'بدون رسوم خفية',
    'schedule.vat.features.2': 'تسعير شفاف',
    'schedule.vat.features.3': 'امتثال كامل',
    'schedule.cta.title': 'هل تحتاج توقيت مخصص؟',
    'schedule.cta.description': 'نفهم أن كل ممتلك له احتياجات جدولة فريدة. تواصل معنا لترتيب جدول عمل مخصص.',
    'schedule.cta.button': 'طلب جدول مخصص',
    'schedule.daily-workflow': 'سير العمل اليومي',
    'schedule.daily-workflow.description': 'شاهد كيف يتكيف جدولنا مع احتياجاتك',
    'schedule.flexible-scheduling': 'جدولة مرنة',
    'schedule.availability': 'التوفر',
    'schedule.availability.description': 'دائماً مستعدون للخدمة',
    'schedule.client-satisfaction': 'رضا العملاء',
    'schedule.client-satisfaction.description': 'وقتك، أولويتنا',
    'schedule.scheduling': 'الجدولة',
    'schedule.scheduling.description': 'تتكيف مع احتياجاتك',
    'schedule.time.custom': 'مخصص',
    'schedule.time.included': 'مشمول',
    'schedule.time.morning': '07:00 - 11:00',
    'schedule.time.evening': '16:00 - 20:00',
    
    // Why Choose Us
    'why.title': 'لماذا نحن',
    'why.quality-title': 'جودة لا تضاهى',
    'why.quality-text': 'نستخدم أفضل المواد والمعدات لضمان نتائج تفوق التوقعات.',
    'why.response-title': 'استجابة سريعة',
    'why.response-text': 'فريقنا جاهز لتلبية احتياجاتك وحل أي طارئ بكفاءة عالية.',
    'why.team-title': 'فريق متكامل',
    'why.team-text': 'فنيون وعمال مدربون لتقديم خدمة احترافية.',
    'why.sustainability-title': 'استدامة وموثوقية',
    'why.sustainability-text': 'نلتزم بالمعايير البيئية ونوفر خدمات يمكنك الاعتماد عليها دائمًا.',
    
    // Contact
    'contact.title': 'تواصل معنا',
    'contact.cta': 'جاهز للارتقاء بممتلكاتك؟ تواصل معنا عبر واتساب الآن لتحديد موعد لتقييم مجاني لمرافقك.',
    'contact.email': 'البريد الإلكتروني',
    'contact.whatsapp-label': 'رقم الواتس',
    'contact.address': 'العنوان',
    'contact.cr-label': 'السجل التجاري',
    'contact.button': 'تحدث معنا على واتساب',
    'contact.address-text': 'الرياض – حي اشبيليا',
    
    // Footer
    'footer.description': 'حلول احترافية للنظافة وإدارة المرافق',
    'footer.links': 'روابط سريعة',
    'footer.contact-info': 'معلومات التواصل',
    'footer.copyright': '© 2024 أمان الخير. جميع الحقوق محفوظة.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Update document direction and lang attribute
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', language === 'ar' ? 'ar' : 'en');
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};